### ISSUE TITLE
Improper parsing

### ISSUE THREAD

**Issue by vorner** [Freyskeyd/xmpp-rs#12]
I noticed this crate on crates.io and not that I'd actually use it, but I have some past experience with XMPP, so I had a look (basically, I was excited to see a tokio-based XMPP library and wondered if it could be of some use in future, to play with).

However, when looking through it, I noticed this code: https://github.com/Freyskeyd/xmpp-rs/blob/master/proto/src/parser.rs#L53. I believe this is mostly wrong approach to parse XMPP streams and it doesn't really work. Simply put, XML is a complex beast and it probably can be proven regular expressions are not powerful enough to handle it.

To point just few problems out:
* You seem to completely ignore namespaces, which is heavily used in XMPP.
* You assume the other side doesn't use namespace prefixes. This, however, isn't always the case ‒ I think google talk at least used things like `<c:message>` and such. And, indeed, the definition of the prefix was on the stream opening element.
* You assume one stanza can't contain an element with the same name. However, things like this are legal:
```xml
<message>
  <message xmlns="my:private:namespace">Stuff here</message>
</message>
```
I believe your regular expression would stop at the first `</message>` and wouldn't form legal stanza of it.

The XML standard has few hundred pages and while XMPP forbids use of parts of it, I still think parsing it manually (especially without first reading the whole beast) can't go well and is an incredible amount of work.

When I worked with XMPP, using a SAX parser (a parser that could be incrementally fed with data and produced a stream of XML events) and building the dom-like trees manually of these worked for me.

**Comment by Freyskeyd** [comment]
Hello,

Thank's for this. In fact the `parser` file is just here to split the buffer into chunk. It's a quick and dirty tricks for now. I would love to have some advice on this part if you can. 

You're suggesting to put the input buffer directly in a XML parser and use namespace to detect stanza right?

**Comment by vorner** [comment]
Well, there are two basic types of XML parsers. The more commonly used is DOM (or a derivate of that) parser. That is, however, not usable in the XMPP situation, because DOM parser needs access to the whole document (it converts it into an in-memory tree structure) and the XMPP stream is always missing the end.

The other type is SAX/stream parser. It can be incrementally fed with parts of the document and it produces „events“ ‒ things like:

 * I've seen the start of element A in namespace X and these attributes.
 * I've seen the start of element B in namespace Y without any attributes.
 * I've seen this bit of text.
 * I've seen another bit of text.
 * I've seen the end of element B.
 * I've seen the whole empty element C in namespace Z.
 * I've seen the end of element A.

The feeding of bits of input is what is handy for the XMPP. What worked for me was to throw away the starting `<stream:stream>` starting element. Then I kept a tree-like structure, the stanza that hasn't finished yet, and a pointer to the current element. When a start of element came, I added it into the current one and descended into it, when an end arrived, I went up through the tree. Whenever I went up from the root element, I produced the stanza, because it was now complete. This part simply constructed the tree structure and store everything (namespaces, attributes, etc). Only the logic in further parts of the library looked at what namespaces and kinds of stanzas these were.

I'm not saying this is the only or best approach, only what I did. It did lead to the goal of being able to communicate with the server, though. But you may have a look at some other existing libraries.

If you want, I can try digging mine out of archives (which might take me a while), but that library never got any actual use, it was only a school project.

**Comment by Freyskeyd** [comment]
I used a library call `elementtree-rs` it's using `xml-rs` underneath. it works well (also with streamed data). But the main issue is how to handle `<stream:stream>` in fact.

To demonstrate how it works, the `decode` method is called when some bytes are push to the stream:

```rust
fn decode(&mut self, buf: &mut BytesMut) -> Result<Option<Self::Item>, io::Error> {
        let mut buff = buf.as_ref();
        // Buffer are parsed, imagine we get an uncomplete IQ, 
        // Element ready will try to parse the buffer but it gonna fail
        // Next iteration we will try again.
        match Element::from_reader(&mut buff) {
            Ok(element) => {
                 // A valid XML elemen with their childrens.
            },
            Err(e) => {
                // Something wrong append (not a full xml element or stream:stream
                // Dealing with it
            }
        };

        return Ok(None);
}
```

I think I can handle the issue with stream data with this kind of solution. But I would like some more information about XMPP namespaces, should I only check namespaces? 

Thank's, if you have some documents (more consistent than XEP/RFC) I'm interested.

**Comment by Freyskeyd** [comment]
When you say @vorner, Google use `<c:message>` you mean:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" to="example.com" version="1.0">
   <stream:stream from="example.com" id="someid" version="1.0">
      <message xmlns:c="my:private:namespace" from="juliet@example.com" to="romeo@example.net" xml:lang="en">
         <body>Art thou not Romeo, and a Montague?</body>
         <c:message>something</c:message>
      </message>
   </stream:stream>
</stream:stream>
```

`message`, `iq` and `presence` always refer to the `xmlns` from `stream:stream`.
Right?

**Comment by vorner** [comment]
What is inconsistent about the XEP/RFC? I found them OK.

Anyway, they are not XMPP namespaces but XML namespaces. It is an XML mechanism to have elements from multiple vendors in the same document and not clash. The idea is that the namespace says what standard or entity defines the element and it is up to that standard to describe what names of tags and attributes are allowed and what they mean.

In the XMPP world, the namespace says what XEP the element belongs to and the name is then described there. So you need to check *both* namespaces and tag names, but the namespaces should be checked first.

As for the example, what you show is somewhat completely odd (two streams inside each other?).

This is the „usual“ stream you can see:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" to="example.com" version="1.0">
  <message from="juliet@example.com"><body>…</body></message>
</stream:stream>
```

In this case, `stream` is in the namespace `http://etherx.jabber.org/streams`, while the rest is inside `jabber:client` namespace.

This is *equivalent* encoding of the same document, as provided by the google talk servers:

```xml
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns:c="jabber:client" to="example.com" version="1.0">
  <c:message from="juliet@example.com"><c:body>…</c:body></c:message>
</stream:stream>
```

The difference is, the `jabber:client` namespace is not defined as default/inherited, but as a prefix that is applied per-element. However, the semantics of both documents is the same. And, obviously, the `c` prefix is arbitrary and the sender can choose any they like.

**Comment by Freyskeyd** [comment]
Hello,

I tried to implement a new way to parse the buffer. I use a side Buffer to hold the entier stream and parse it with `xml-rs`.

You can check that the codec is feeding a buffer with new bytes: https://github.com/Freyskeyd/xmpp-rs/blob/ping_result/proto/src/codec.rs#L57

After that the codec call the parser and ask for the next event: https://github.com/Freyskeyd/xmpp-rs/blob/ping_result/proto/src/codec.rs#L61

The parser is a struct that hold a EventReader (from `xml-rs`) and read the buffer fed by the codec:  https://github.com/Freyskeyd/xmpp-rs/blob/ping_result/proto/src/parser/mod.rs#L32

I would like your advise on how I use and detect stanza, here's an example of how I detect a `stream:features`:

```rust
match self.parser.next() {
  Ok(xml_event) => {
    match xml_event {
      XmlEvent::StartElement { name, namespace, attributes} => {
        // name.local_name represent the `features` in `<XXX:features>`
        // name.namespace_ref represent the current namespace of the element which is defined on `XXX:stream` in that case
        if name.local_name == "features" && name.namespace_ref() == Some(ns::STREAM) {
          ...
        }
      }
    }
  }
}
```

**Comment by vorner** [comment]
I get „Page not found“ errors when trying to look at the links. Is it possible you renamed/removed the branch?

Do you really try to keep the whole stream, from the start to the current position, in a buffer? Even when it is potentially infinite? I'm afraid that might eat a lot of memory as the time goes.

What do you mean, detect a stanza? A stanza is a direct child of the `<stream>` element.

I think you try to do a lot of things at the same level of abstraction. It's not exactly wrong, but I have some problems reasoning about it that way… I believe it's better to first build the stanzas as some objects (eg. something like DOM representations) and then try to match these objects to handlers, in some generic way.

Or are you asking how to match them? Yes, checking both on the namespace and the element name works. I'd probably have some „registry“ (eg a hash map) from stanza type (message/iq/presence), namespace and name to something that can consume them.

**Comment by Freyskeyd** [comment]
In fact I already update master and you can check all modification in [codec](https://github.com/Freyskeyd/xmpp-rs/blob/master/proto/src/codec.rs) and [parser](https://github.com/Freyskeyd/xmpp-rs/blob/master/proto/src/parser/mod.rs).

I use a Buffer (from Circular) which hold every bytes until no space left, then it start cleaning the start of the buffer. But I need to check how `xml-rs` works, I hope that they just keep a Hashmap of every namespaces not the all buffer that was read.

I think you describe exactly what I'm doing, I will explain how it works:

When a `stanza` (an IQ result in our example) sent by the server is read by the client:
- Codec will feed every bytes into the parser
- The parser will tell xml-rs to try to read a need XMLElement
- The parser will detect an XMLElement and define it as a GenericIQ based on namespace and local-name.
- This GenericIQ is receive by the internal connection handler, and converted as an IqEvent of type Result.
- Then this IqEvent is pushed to the end client to be consume.

In fact I'm not dealing with the parsing/detection/validation of new XMLElements. thank's to xml-rs.

**Comment by vorner** [comment]
Sorry for taking so long. This one looks much less ad-hoc than the original and I think it should work.

One very minor thing I noticed ‒ I think that `write` in `XmppParser::feed` might write less data than the whole buffer if it doesn't fit. Also, the removing of `/>` in `Codec` seems a bit suspicious but I see a TODO there :-).
