### ISSUE TITLE
Extensible XMPP for Rust?

### ISSUE THREAD

**Issue by SoniEx2** [Freyskeyd/xmpp-rs#23]
XMPP is supposed to be extensible. Is this crate extensible?

You shouldn't have to implement the extensions/plugins/whatever in the core crate, neither should the core crate need to be aware of the extensions. Is this the case?

**Comment by Freyskeyd** [comment]
Hello @SoniEx2 ,

This project isn't really active for now. (Too many things to do at work :( )

It doesn't support plugins/extensions.

**Comment by SoniEx2** [comment]
Have you considered moving everything to plugins/extensions? Like, getting rid of the monolithic and implementing only the basic functionality? Letting everyone else implement all the non-core RFCs?

**Comment by Freyskeyd** [comment]
I'm investigating actor system to deal with this.

Have you any input about that?

**Comment by SoniEx2** [comment]
Honestly I'm also trying to figure it out - I need it so I can make a base IRC library and let someone else deal with IRCv3. (I'd also make a CTCP/CTCP-S crate myself, but that's beside the point.)

**Comment by SoniEx2** [comment]
Would you like to come on IRC and see if we can work something out?

**Comment by SoniEx2** [comment]
I have this idea but it may be a bad idea but basically could something like this be done here?

https://github.com/aatxe/irc/issues/107#issuecomment-354920366
